// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shipping.Api.Data;

#nullable disable

namespace Shipping.Api.Data.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    partial class ShippingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipping")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shipping.Api.Domain.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<DateTime?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("LabelUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("label_url");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("ProviderShipmentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_shipment_id");

                    b.Property<string>("ProviderTrackerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_tracker_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tracking_number");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DestinationAddress", "Shipping.Api.Domain.Shipment.DestinationAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(10);

                            b1.Property<string>("PostalCode")
                                .IsRequired();

                            b1.Property<string>("SecondaryStreet");

                            b1.Property<string>("State")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1
                                .ToJson("destination_address")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dimensions", "Shipping.Api.Domain.Shipment.Dimensions#PackageDimensions", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Height", "Shipping.Api.Domain.Shipment.Dimensions#PackageDimensions.Height#Length", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(10);

                                    b2.Property<decimal>("Value");

                                    b2
                                        .ToJson("height")
                                        .HasColumnType("jsonb");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Length", "Shipping.Api.Domain.Shipment.Dimensions#PackageDimensions.Length#Length", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(10);

                                    b2.Property<decimal>("Value");

                                    b2
                                        .ToJson("length")
                                        .HasColumnType("jsonb");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Width", "Shipping.Api.Domain.Shipment.Dimensions#PackageDimensions.Width#Length", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(10);

                                    b2.Property<decimal>("Value");

                                    b2
                                        .ToJson("width")
                                        .HasColumnType("jsonb");
                                });

                            b1
                                .ToJson("dimensions")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OriginAddress", "Shipping.Api.Domain.Shipment.OriginAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(10);

                            b1.Property<string>("PostalCode")
                                .IsRequired();

                            b1.Property<string>("SecondaryStreet");

                            b1.Property<string>("State")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1
                                .ToJson("origin_address")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SelectedRate", "Shipping.Api.Domain.Shipment.SelectedRate#ShippingRateQuote", b1 =>
                        {
                            b1.Property<string>("Carrier")
                                .IsRequired();

                            b1.Property<int?>("EstDeliveryDays");

                            b1.Property<decimal>("Price");

                            b1.Property<string>("ProviderRateId")
                                .IsRequired();

                            b1.Property<string>("Service")
                                .IsRequired();

                            b1
                                .ToJson("selected_rate")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Weight", "Shipping.Api.Domain.Shipment.Weight#Weight", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(10);

                            b1.Property<decimal>("Value");

                            b1
                                .ToJson("weight")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_shipments_order_id");

                    b.HasIndex("ProviderShipmentId")
                        .HasDatabaseName("ix_shipments_provider_shipment_id");

                    b.HasIndex("TrackingNumber")
                        .HasDatabaseName("ix_shipments_tracking_number");

                    b.ToTable("shipments", "shipping");
                });

            modelBuilder.Entity("Shipping.Api.Domain.ShipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_shipment_items");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_shipment_items_shipment_id");

                    b.ToTable("shipment_items", "shipping");
                });

            modelBuilder.Entity("Shipping.Api.Domain.TrackingMilestone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("location");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tracking_milestones");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_tracking_milestones_shipment_id");

                    b.ToTable("tracking_milestones", "shipping");
                });

            modelBuilder.Entity("Shipping.Api.Domain.ShipmentItem", b =>
                {
                    b.HasOne("Shipping.Api.Domain.Shipment", null)
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_items_shipments_shipment_id");
                });

            modelBuilder.Entity("Shipping.Api.Domain.TrackingMilestone", b =>
                {
                    b.HasOne("Shipping.Api.Domain.Shipment", null)
                        .WithMany("TrackingMilestones")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tracking_milestones_shipments_shipment_id");
                });

            modelBuilder.Entity("Shipping.Api.Domain.Shipment", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("TrackingMilestones");
                });
#pragma warning restore 612, 618
        }
    }
}
